- name: "Proxmox: set netif (LXC)"
  connection: local
  hosts: all
  gather_facts: False

  vars:
    collected_proxmox_vm: {}
    collected_proxmox_lxc: {}

  tasks:
  - name: Include Proxmox VM discovery
    include_tasks: "ansible-tasks/collect-proxmox-vm.yml"

  - name: Include Proxmox LXC discovery
    include_tasks: "ansible-tasks/collect-proxmox-lxc.yml"

  - name: "Update LXC settings (netif)"
    community.general.proxmox:
      node: "{{ proxmox_env_info.node }}"
      api_user: "{{ proxmox_env_info.api_user }}"
      api_token_id: "{{ proxmox_env_info.api_token_id }}"
      api_token_secret: "{{ proxmox_env_info.api_token_secret }}"
      api_host: "{{ proxmox_env_info.api_host }}"
      hostname: "{{ vm_config['hostname'] }}"
      vmid: "{{ collected_proxmox_lxc[vm_config['hostname']] | int }}"
      netif:
        #ipconfig0: "ip={{ item.ip }},gw={{ item.ip.split('.')[:3] | join('.') }}.{{ item.gw if item.gw is defined else gw_last_quad }}"
        net0: "name=eth0,ip={{ vm_config['ip'] }},gw={{ vm_config['ip'].split('.')[:3] | join('.') }}.1,bridge=vmbr0,firewall=1"
      update: true
    when: vm_config['hostname'] in collected_proxmox_lxc
    register: update_lxc_settings_job
    async: 180
    poll: 0

  - name: Wait for VM settings updates processes to finish
    async_status:
      jid: "{{ update_lxc_settings_job.ansible_job_id }}"
    when: vm_config['hostname'] in collected_proxmox_lxc
    register: _ujobs_alias_vc_0
    until: _ujobs_alias_vc_0.finished
    retries: 60
    delay: 10

