- name: "NetBox-Proxmox VM Manager"
  connection: local
  hosts: localhost
  gather_facts: False
  
  vars:
    collected_proxmox_vms: {}
    proxmox_vm_create: []
    proxmox_vm_delete: []
    proxmox_all_vm_interfaces: {}
    proxmox_vm_interfaces_prefix: []
    proxmox_vm_interfaces_ip: []
    nb_vm_inventory: {}
    nb_vm_inventory_staged: {}
    nb_vm_created: {}
    nb_vm_interface_assigned_ip: {}
    nb_remove_vms: {}
    nb_vm_config_disks: []
    nb_vm_collected_disks: []
    nb_vm_active: []
    nb_vm_stopped: []
    nb_vm_decomissioning: []
    nb_dns_plugin_zn: {}
    nb_dns_plugin_soa: {}
    nb_dns_plugin_ns: {}
    nb_dns_plugin_mx: {}
    nb_dns_plugin_mx_dol: []
    nb_dns_plugin_rr: {}
    nb_dns_plugin_rr_dol: []
    nb_dns_plugin_changed: false
    tmp_dns_zone_dir: ''    
    proxmox_ipconfig_dict: {}
    gw_last_quad: 1

  tasks:
  - name: Collect secrets
    include_vars:
      file: secrets.yml
      name: secrets_cfg

  - name: Read Proxmox VM Configuration
    include_vars:
      file: vms.yml
      name: proxmox_vm_cfg

  - name: Init dict(s)
    set_fact:
      vm_config: {}
      vm_config_interfaces: {}
      vm_config_remove: {}
      the_fact: {}
      nb_selected_vm: ''
      nb_selected_interface: ''
      nb_ipconfig_key_name: ''
      remote_bind9_zone_db_directory: "{{ proxmox_vm_cfg.remote_bind9_zone_db_directory }}"

  - name: "Proxmox: Discover VMs"
    include_tasks: "ansible-tasks/proxmox/discover-vms.yml"

  - name: "NetBox: Check Prefix and IP settings for Proxmox VMs"
    include_tasks: "ansible-tasks/netbox/prefix-ip-checker.yml"

  - name: Collect VM(s) to create/start
    set_fact:
      vm_config: "{{ vm_config | combine({item.name: {'template': item.template, 'vcpus': item.vcpus, 'memory': item.memory, 'disks': item.disks, 'sshkey': item.sshkey, 'storage': item.storage if item.storage is defined else proxmox_vm_cfg.default_storage, 'start': item.start if item.start is defined else default_vm_start_state, 'gw': item.gw if item.gw is defined else gw_last_quad}}) }}"
    with_items: "{{ proxmox_vm_cfg.vms }}"
    when: item.exists

  - name: Collect VM(s) to remove
    set_fact:
      vm_config_remove: "{{ vm_config_remove | combine({item.name: True }) }}"
    with_items: "{{ proxmox_vm_cfg.vms }}"
    when: not item.exists

  - name: "NetBox: Collect VMs (pre)"
    include_tasks: "ansible-tasks/netbox/check-vms.yml"
  
  - name: "NetBox: Create (Proxmox) VMs"
    include_tasks: "ansible-tasks/netbox/create-vms.yml"

  - name: "NetBox: Create (Proxmox) VMs Network Interfaces"
    include_tasks: "ansible-tasks/netbox/create-network-interfaces.yml"

  - name: "NetBox: Create IPs (by prefix) for (Proxmox) VMs Network Interfaces"
    include_tasks: "ansible-tasks/netbox/create-ips-by-prefix.yml"

  - name: "NetBox: Create IPs (static) for (Proxmox) VMs Network Interfaces"
    include_tasks: "ansible-tasks/netbox/create-static-ips.yml"

  - name: "NetBox: Update primary_ip4 for (Proxmox) VMs"
    include_tasks: "ansible-tasks/netbox/update-primary-ip4.yml"

  - name: "NetBox: Add disks to VMs"
    include_tasks: "ansible-tasks/netbox/create-vms-disks.yml"

  - name: "NetBox: Collect VMs (post)"
    include_tasks: "ansible-tasks/netbox/check-vms.yml"

  - name: "NetBox: Staged VM inventory"
    include_tasks: "ansible-tasks/netbox/get-staged-vm-status.yml"

  - name: "Proxmox: Clone VMs"
    include_tasks: "ansible-tasks/proxmox/clone-vms.yml"

  - name: "Proxmox: VMs update resource settings (CPU, memory, etc)"
    include_tasks: "ansible-tasks/proxmox/vm-resource-settings.yml"

  - name: "Proxmox: VMs update sshkeys settings"
    include_tasks: "ansible-tasks/proxmox/vm-ssh-key-settings.yml"

  - name: "Proxmox: VMs IP address settings"
    include_tasks: "ansible-tasks/proxmox/vm-ip-settings.yml"

  - name: "Proxmox: Grow VM disks"
    include_tasks: "ansible-tasks/proxmox/grow-vm-disk.yml"

  - name: "Proxmox: Add VM disks"
    include_tasks: "ansible-tasks/proxmox/add-vm-disks.yml"

  - name: "NetBox: Set specified VMs to Active"
    include_tasks: "ansible-tasks/netbox/set-vms-active.yml"

  - name: "NetBox: Find DNS zones via netbox-dns plugin"
    include_tasks: "ansible-tasks/netbox/find-dns-zones.yml"
    when: proxmox_vm_cfg is defined and proxmox_vm_cfg.update_dns

  - name: "NetBox: Create DNS entries via netbox-dns plugin"
    include_tasks: "ansible-tasks/netbox/create-dns-record.yml"
    when: proxmox_vm_cfg is defined and proxmox_vm_cfg.update_dns

  - name: "NetBox: Find DNS zones SOA via netbox-dns plugin"
    include_tasks: "ansible-tasks/netbox/find-dns-zones-info.yml"
    when: proxmox_vm_cfg is defined and proxmox_vm_cfg.update_dns

  - name: "Proxmox: Start specified VMs"
    include_tasks: "ansible-tasks/proxmox/start-vms.yml"

  - name: "BIND9: Create (DNS) zone dbs"
    include_tasks: "ansible-tasks/dns/bind9/create-zone-files.yml"
    when: proxmox_vm_cfg is defined and proxmox_vm_cfg.update_dns is defined and proxmox_vm_cfg.update_dns and 'bind9' in proxmox_vm_cfg.dns_integrations

  - meta: end_play

  - name: "Proxmox: Stop specified VMs"
    include_tasks: "ansible-tasks/proxmox/stop-vms.yml"

  - name: "Proxmox: Remove specified VMs"
    include_tasks: "ansible-tasks/proxmox/remove-vms.yml"

- name: "bind9: propagate DNS changes"
  connection: paramiko
  hosts: dns
  gather_facts: False

  tasks:
    - name: Copy Bind9 (DNS) zone files
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ hostvars['localhost']['remote_bind9_zone_db_directory'] }}"
        owner: "bind"
        group: "bind"
        mode: 0600
      with_fileglob:
        - "{{ hostvars['localhost']['tmp_dns_zone_dir'] }}/db.*"
      when: hostvars['localhost']['nb_dns_plugin_changed'] is defined and hostvars['localhost']['nb_dns_plugin_changed'] and hostvars['localhost']['tmp_dns_zone_dir'] is defined
      notify:
        - Restart bind9

  handlers:
    - name: Restart bind9
      become: true
      service:
        name: bind9
        state: restarted
      when: hostvars['localhost']['nb_dns_plugin_changed'] is defined and hostvars['localhost']['nb_dns_plugin_changed']

- name: Clean up
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
  - name: "BIND9: remove temporary (DNS) zone db files"
    include_tasks: "ansible-tasks/dns/bind9/clean-up-temp-directory.yml"
