---
- name: Read VMS YAML
  hosts: localhost

  vars:
    gw_last_quad: 1

  tasks:
    - name: read it
      include_vars:
        file: vms.yml
        name: stuff

    - debug:
        msg: "stuff is {{ stuff }}"

    - debug:
        msg: "{{ item.name }} | {{ lookup('file', item.sshkey) }} | ip: {{ item.ip }} | gateway: {{ item.ip.split('.')[:3] | join('.') }}.{{ item.gw if item.gw is defined else gw_last_quad }}"
      loop: "{{ stuff.vms }}"


