---
- name: STOP VM TASKS
  hosts: proxmox

  tasks:
  - name: Read secrets from configuration
    include_vars:
      file: secrets.yml
      name: secrets_cfg

  - name: Read Proxmox VM Configuration
    include_vars:
      file: vms.yml
      name: proxmox_vm_cfg

  - name: Set arr for configured Proxmox VMs
    set_fact:
      cfg_vms: []

  - name: Set arr for Proxmox VMs status
    set_fact:
      cfg_vms_status: []

  - name: Collect configured VM names
    set_fact:
      cfg_vms: "{{ cfg_vms + [ item.name ] }}"
    with_items: "{{ proxmox_vm_cfg.vms }}"
    when: not item.exists

  - name: Get status of VMs
    community.general.proxmox_vm_info:
      node: "{{ secrets_cfg.proxmox.node }}"
      api_user: "{{ secrets_cfg.proxmox.api_user }}"
      api_token_id: "{{ secrets_cfg.proxmox.api_token_id }}"
      api_token_secret: "{{ secrets_cfg.proxmox.api_token_secret }}"
      api_host: "{{ secrets_cfg.proxmox.api_host }}"
      name: "{{ item.name }}"
      type: qemu
    with_items: "{{ proxmox_vm_cfg.vms }}"
    when: not item.exists
    register: vm_status

  - name: Collect running VM names from status
    set_fact:
        cfg_vms_status: "{{ cfg_vms_status + item.proxmox_vms }}"
    with_items: "{{ vm_status.results }}"
    when: item.proxmox_vms is defined
    register: bung

  - name: Stop specified VMs
    community.general.proxmox_kvm:
      node: "{{ secrets_cfg.proxmox.node }}"
      api_user: "{{ secrets_cfg.proxmox.api_user }}"
      api_token_id: "{{ secrets_cfg.proxmox.api_token_id }}"
      api_token_secret: "{{ secrets_cfg.proxmox.api_token_secret }}"
      api_host: "{{ secrets_cfg.proxmox.api_host }}"
      name: "{{ item.name }}"
      state: stopped
      force: true
    with_items: "{{ cfg_vms_status }}"
    register: stop_vms_job
    async: 180
    poll: 0

  - name: Wait for VM stop processes to finish
    async_status:
     #id: "{{ item.ansible_job_id }}"
      jid: "{{ item.ansible_job_id }}" # ansible version > 2.8
    register: _sjobs_alias_vc_0
    until: _sjobs_alias_vc_0.finished
    retries: 100
    delay: 10
    with_items: "{{ stop_vms_job.results }}"
    when: item.ansible_job_id is defined and not item.finished

  - name: Remove specified VMs
    community.general.proxmox_kvm:
      node: "{{ secrets_cfg.proxmox.node }}"
      api_user: "{{ secrets_cfg.proxmox.api_user }}"
      api_token_id: "{{ secrets_cfg.proxmox.api_token_id }}"
      api_token_secret: "{{ secrets_cfg.proxmox.api_token_secret }}"
      api_host: "{{ secrets_cfg.proxmox.api_host }}"
      vmid: "{{ item.vmid }}"
      state: absent
      force: true
    with_items: "{{ _sjobs_alias_vc_0.results }}"
    register: remove_vms_job
    async: 180
    poll: 0

  - name: Wait for VM removal
    async_status:
      #id: "{{ item.ansible_job_id }}"
      jid: "{{ item.ansible_job_id }}" # ansible version > 2.8
    register: _rjobs_alias_vc_0
    until: _rjobs_alias_vc_0.finished
    retries: 100
    delay: 5
    with_items: "{{ remove_vms_job.results }}"
    when: item.ansible_job_id is defined
