  - name: Find VMs in Netbox
    ansible.builtin.uri:
      url: "{{ secrets_cfg.netbox.api_proto }}://{{ secrets_cfg.netbox.api_host }}:{{ secrets_cfg.netbox.api_port}}/api/virtualization/virtual-machines/"
      method: GET
      headers:
        Authorization: "Token {{ secrets_cfg.netbox.api_token }}"
        Accept: application/json
        Content-Type: application/json
      status_code: 200
      validate_certs: no
    register: netbox_find_vms

  - name: Store NetBox VM inventory
    set_fact:
      nb_vm_inventory: "{{ nb_vm_inventory | combine({item.name: True}) }}"
    with_items: "{{ netbox_find_vms.json.results }}"
