  - name: Create temporary build directory
    ansible.builtin.tempfile:
      state: directory
      suffix: build
    when: nb_dns_plugin_changed
    register: tmp_bind9_zones_dir

  - name: Set temporary build directory variable
    set_fact:
      tmp_dns_zone_dir: "{{ tmp_bind9_zones_dir.path }}"
    when: nb_dns_plugin_changed

#  - name: Show bind9 tmp zones dir
#    debug:
#      msg: "bind9 tmp zones dir: {{ tmp_bind9_zones_dir }} ||| {{ tmp_dns_zone_dir }}"

  - name: Create DNS zone files (bind9)
    ansible.builtin.template:
      src: templates/dns/zone-template.j2
      dest: "{{ tmp_dns_zone_dir }}/db.{{ item }}"
    with_items: "{{ nb_dns_plugin_zn }}"
    when: nb_dns_plugin_changed

