  - name: Update VM settings for IP addresses
    community.general.proxmox_kvm:
      node: "{{ secrets_cfg.proxmox.node }}"
      api_user: "{{ secrets_cfg.proxmox.api_user }}"
      api_token_id: "{{ secrets_cfg.proxmox.api_token_id }}"
      api_token_secret: "{{ secrets_cfg.proxmox.api_token_secret }}"
      api_host: "{{ secrets_cfg.proxmox.api_host }}"
      name: "{{ item }}"
      ipconfig:
        #ipconfig0: "ip={{ nb_vm_interface_assigned_ip[item].ip }},gw={{ nb_vm_interface_assigned_ip[item].ip.split('.')[:3] | join('.') }}.{{ item.gw if item.gw is defined else gw_last_quad }}"
        #"{{ proxmox_ipconfig_dict[item] }}"
        ipconfig0: "ip={{ nb_vm_inventory_staged[item].ip }},gw={{ nb_vm_inventory_staged[item].ip.split('.')[:3] | join('.') }}.{{ item.gw if item.gw is defined else gw_last_quad }}"
      update: true
    with_items: "{{ nb_vm_inventory_staged }}"
    when: not item in collected_proxmox_vms and item in nb_vm_inventory_staged
    register: update_vms_settings_job
    async: 180
    poll: 0

  - name: Wait for VM settings updates processes to finish
    async_status:
      #id: "{{ item.ansible_job_id }}"
      jid: "{{ item.ansible_job_id }}" # ansible version > 2.8
    register: _ujobs_alias_vc_0
    until: _ujobs_alias_vc_0.finished
    retries: 60
    delay: 10
    with_items: "{{ update_vms_settings_job.results }}"
    when: item.ansible_job_id is defined
