- name: "NetBox-Proxmox VM Manager"
  connection: local
  hosts: localhost
  gather_facts: False
  
  vars:
    collected_proxmox_vms: {}
    proxmox_vm_create: []
    proxmox_vm_delete: []
    proxmox_all_vm_interfaces: {}
    proxmox_vm_interfaces_prefix: []
    proxmox_vm_interfaces_ip: []
    nb_vm_created: {}
    nb_vm_interface_assigned_ip: {}
    nb_remove_vms: {}
    proxmox_ipconfig_dict: {}
    gw_last_quad: 1

  tasks:
  - name: Collect secrets
    include_vars:
      file: secrets.yml
      name: secrets_cfg

  - name: Read Proxmox VM Configuration
    include_vars:
      file: vms.yml
      name: proxmox_vm_cfg

  - name: Init dict(s)
    set_fact:
      vm_config: {}
      vm_config_interfaces: {}
      vm_config_remove: {}
      the_fact: {}
      nb_selected_vm: ''
      nb_selected_interface: ''
      nb_ipconfig_key_name: ''

  - name: "NetBox: Configure base objects from defaults"
    include_tasks: "ansible-tasks/netbox/netbox-object-defaults.yml"

  - name: "NetBox: Configure base objects from vm settings"
    include_tasks: "ansible-tasks/netbox/netbox-vm-object-defaults.yml"

  - name: "NetBox: Configure base objects for VM clusters"
    include_tasks: "ansible-tasks/netbox/netbox-vm-cluster-objects.yml"

  - name: "Proxmox: Discover VMs"
    include_tasks: "ansible-tasks/proxmox/discover-vms.yml"

  - name: "NetBox: Check Prefix and IP settings for Proxmox VMs"
    include_tasks: "ansible-tasks/netbox/prefix-ip-checker.yml"
